on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install numpy
        run: pip install numpy

      - name: Install pandas
        run: pip install pandas

      - name: Install scikit-learn
        run: pip install scikit-learn

      - name: Install matplotlib
        run: pip install matplotlib

      - name: Install seaborn
        run: pip install seaborn

      - name: Install jupyter
        run: pip install jupyter

      - name: Install pytest
        run: pip install pytest

      - name: Install flake8
        run: pip install flake8

      - name: Run tests
        run: pytest
