on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Conda
        run: |
          wget -O ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash ~/miniconda.sh -b -p ~/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          conda init bash
          conda create -n myenv python=3.8 -y
          conda activate myenv
          conda install numpy pandas scikit-learn matplotlib seaborn jupyter pytest flake8 -y
